# Generated by Django 3.2.16 on 2022-10-23 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApartmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Restrict',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField()),
                ('address', models.CharField(max_length=100)),
                ('coordinate', models.CharField(max_length=50)),
                ('scroe', models.SmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('apartment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartmenttype')),
                ('device', models.ManyToManyField(to='apartment.Device')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.district')),
                ('rent_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.renttype')),
                ('restrict', models.ManyToManyField(to='apartment.Restrict')),
                ('room_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.roomtype')),
            ],
        ),
    ]
