# Generated by Django 3.2.16 on 2022-10-26 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0003_rename_scroe_apartment_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacilityType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'db_table': 'apartment_facility_types',
            },
        ),
        migrations.RemoveField(
            model_name='apartment',
            name='score',
        ),
        migrations.AddField(
            model_name='apartment',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='url',
            field=models.URLField(max_length=300),
        ),
        migrations.AlterModelTable(
            name='apartment',
            table='apartment_apartments',
        ),
        migrations.AlterModelTable(
            name='apartmenttype',
            table='apartment_apartment_types',
        ),
        migrations.AlterModelTable(
            name='device',
            table='apartment_devices',
        ),
        migrations.AlterModelTable(
            name='renttype',
            table='apartment_rent_types',
        ),
        migrations.AlterModelTable(
            name='restrict',
            table='apartment_restricts',
        ),
        migrations.AlterModelTable(
            name='roomtype',
            table='apartment_room_types',
        ),
        migrations.CreateModel(
            name='SurroundingFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('apartment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.apartment')),
                ('facility_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apartment.facilitytype')),
            ],
            options={
                'db_table': 'apartment_surrounding_facilities',
            },
        ),
    ]
