# Generated by Django 3.2.16 on 2022-10-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0004_auto_20221026_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apartment',
            options={'verbose_name': 'apartment', 'verbose_name_plural': 'apartments'},
        ),
        migrations.AlterModelOptions(
            name='apartmenttype',
            options={'verbose_name': 'apartment_type', 'verbose_name_plural': 'apartment_types'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'device', 'verbose_name_plural': 'devices'},
        ),
        migrations.AlterModelOptions(
            name='facilitytype',
            options={'verbose_name': 'facility_type', 'verbose_name_plural': 'facility_types'},
        ),
        migrations.AlterModelOptions(
            name='renttype',
            options={'verbose_name': 'rent_type', 'verbose_name_plural': 'rent_types'},
        ),
        migrations.AlterModelOptions(
            name='restrict',
            options={'verbose_name': 'restrict', 'verbose_name_plural': 'restricts'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'verbose_name': 'room_type', 'verbose_name_plural': 'room_types'},
        ),
        migrations.AlterModelOptions(
            name='surroundingfacility',
            options={'verbose_name': 'surrounding_facility', 'verbose_name_plural': 'surrounding_facilities'},
        ),
    ]
