# Generated by Django 3.2.16 on 2022-10-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartment', '0005_auto_20221026_0537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='device',
            field=models.ManyToManyField(blank=True, to='apartment.Device'),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='restrict',
            field=models.ManyToManyField(blank=True, to='apartment.Restrict'),
        ),
    ]
