# Generated by Django 3.2.16 on 2022-10-24 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(blank=True, max_length=300),
        ),
    ]
