# Generated by Django 3.2.16 on 2022-10-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_auto_20221026_0125'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='benefit',
            options={'verbose_name': 'benefit', 'verbose_name_plural': 'benefits'},
        ),
        migrations.AlterModelOptions(
            name='city',
            options={'verbose_name': 'city', 'verbose_name_plural': 'cities'},
        ),
        migrations.AlterModelOptions(
            name='district',
            options={'verbose_name': 'district', 'verbose_name_plural': 'districts'},
        ),
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'job', 'verbose_name_plural': 'jobs'},
        ),
        migrations.AlterModelOptions(
            name='jobposition',
            options={'verbose_name': 'job_position', 'verbose_name_plural': 'job_positions'},
        ),
        migrations.AlterModelOptions(
            name='workinghour',
            options={'verbose_name': 'working_hour', 'verbose_name_plural': 'working_hours'},
        ),
    ]
